export LAB="vlab3.dyndns.org"
#export SFTPSERVER="rber@gateone-1:/tmp"
#export LAB="vlab1.dyndns.org"
#export SFTPSERVER="rber@t530-1-kvm-gateone-1:/tmp"
export SFTPSERVER="rber@vlab3.dyndns.org:/tmp"
